import type { NewsEvent } from "$lib/types";

/**
 * News is curated from the team's own sites. Pictures and write-ups stay
 * there, and every entry here links through to the fuller story.
 */

const anil = (slug: string) => `https://anil.recoil.org/notes/${slug}`;
const sam = (path: string) => `https://www.samreynolds.org/${path}`;

/** Responsive variants generated by anil.recoil.org for every image. */
const anilImg = (name: string, alt: string) => ({
  src: `https://anil.recoil.org/images/${name}.640.webp`,
  srcset: [320, 640, 1024]
    .map((w) => `https://anil.recoil.org/images/${name}.${w}.webp ${w}w`)
    .join(", "),
  alt
});

export const events: NewsEvent[] = [
  {
    date: "2026-09-07",
    title: "AI and rapid evidence reviews at the DEFRA data festival",
    detail:
      "Sam Reynolds leads a workshop at the DEFRA Group Data and Information Festival in London.",
    kind: "workshop",
    url: sam("#talks")
  },
  {
    date: "2026-08-09",
    title: "The Conservation Copilot takes shape",
    detail:
      "The team advanced the Conservation Copilot, a layer over the evidence-synthesis pipeline, in step with a major overhaul of the shared paper storage and classification infrastructure that underpins it.",
    kind: "milestone",
    url: anil("2026w32#evidence-tap")
  },
  {
    date: "2026-08-02",
    title: "Building the literature pipeline for Evidence TAP",
    detail:
      "Work on Taposaur, the project's processing pipeline: a custom downloader that navigates publisher access, and a GROBID-based metadata index over millions of full-text papers, giving the Copilot secure, local-model-only access to the corpus.",
    kind: "milestone",
    url: anil("2026w31#arise-taposaur-and-obtain-the-literature-for-evidence-tap"),
    picture: anilImg(
      "taposaur-ss-1",
      "The Taposaur index dashboard, showing GROBID and TEI conversion progress across 3.3 million papers"
    )
  },
  {
    date: "2026-07-26",
    title: "A public home for Evidence TAP",
    detail:
      "With growing interest from policymakers in living evidence databases, the project began putting together this public website to explain the approach.",
    kind: "milestone",
    url: anil("2026w30#prototyping-the-evidence-tap-website-with-an-agent")
  },
  {
    date: "2026-07-20",
    title: "Principles for responsible AI in conservation",
    detail:
      "Sam Reynolds led a preprint with conservation-AI researchers worldwide. It has been submitted to Conservation Science and Practice.",
    kind: "paper",
    url: sam("notes.html#2026-07-20-principles-for-responsible-ai-in-conservation"),
    picture: {
      src: "https://www.samreynolds.org/images/notes/Image%20(28).jpeg",
      alt: "Co-authors of the responsible AI principles paper outside the Oxford Martin School"
    }
  },
  {
    date: "2026-07-19",
    title: "Evidence TAP takes shape",
    detail:
      "Project paperwork lands and regular meetings begin: Eleanor Toye Scott joins to organise the living evidence database design requirements, alongside the conservation and education teams.",
    kind: "milestone",
    url: anil("2026w29#evidence-tap-starts-taking-shape"),
    picture: anilImg(
      "etap-26-1",
      "The Evidence TAP team meeting at the Centre for the Study of Existential Risk"
    )
  },
  {
    date: "2026-07-06",
    title: "Plenary panel at ECCB 2026",
    detail:
      "Sam joins the plenary panel on AI at the European Congress of Conservation Biology in Leiden, with live notes from the congress.",
    kind: "talk",
    url: sam("notes.html#2026-07-06-eccb-plenary-panel"),
    picture: {
      src: "https://www.samreynolds.org/images/notes/ECCB1.jpeg",
      alt: "Signboard for ECCB 2026 outside the congress venue in Leiden"
    }
  },
  {
    date: "2026-06-29",
    title: "The Conservation Copilot demoed in Parliament",
    detail:
      "Alec Christie, Sam Reynolds and Sadiq Jaffer, with Bill Sutherland, demoed the Evidence TAP traceable AI pipeline at the Georgina Mace Centre for the Living Planet debate at the Houses of Parliament.",
    kind: "talk",
    url: anil("2026w28#conservation-evidence-takes-the-stage-at-parliament"),
    picture: anilImg(
      "hol-nature-1",
      "Demonstrating the Evidence TAP pipeline at the Houses of Parliament"
    )
  },
  {
    date: "2026-06-14",
    title: "World Biodiversity Forum, Davos",
    detail: "Sam presented AI for reviewing conservation evidence at the forum in Davos, Switzerland.",
    kind: "talk",
    url: sam("#talks")
  },
  {
    date: "2026-06-07",
    title: "Evidence TAP kicks off",
    detail:
      "The project held its first meeting on broadening Conservation Evidence into education. Jenny Gibson and Mélanie Gréaux joined the team in Cambridge.",
    kind: "milestone",
    url: anil("2026w23#evidence-tap-kicks-off"),
    picture: anilImg(
      "evitap-education-1",
      "The team meeting around a table at the Faculty of Education in Cambridge"
    )
  },
  {
    date: "2026-05-10",
    title: "Evidence for nature recovery briefed to Parliament",
    detail:
      "POSTnote 767 reports on a briefing that Bill Sutherland, Lynn Dicks and Anil Madhavapeddy gave to the UK Parliament. It sets out how systematic evidence supports the Planning and Infrastructure Act 2025.",
    kind: "milestone",
    url: anil("2026w19#parliamentary-evidence-for-nature-recovery"),
    picture: {
      ...anilImg(
        "26w19-ss-nature",
        "Cover of POSTnote 767, Evidence for Nature Recovery"
      ),
      pos: "top"
    }
  },
  {
    date: "2026-04-22",
    title: "LLMs in government decision making",
    detail:
      "Sadiq Jaffer and Sam Reynolds spoke at the Digital Statecraft Academy on “The inevitable rise of Large Language Models in government decision making”, fielding practical questions from civil servants.",
    kind: "talk",
    url: anil("2026w18#the-inevitable-rise-of-llms-in-government-decision-making"),
    picture: anilImg(
      "digital-statecraft-2",
      "Presenting the evidence synthesis work at the Digital Statecraft Academy"
    )
  },
  {
    date: "2026-03-22",
    title: "Securing full-text access from publishers",
    detail:
      "The TAP's paper downloader needs full text for reproducible, human-in-the-loop annotation. Anil writes about navigating Springer's new premium API and Wiley's AI gateway, alongside evidence synthesis events at DESNZ and a Nature-hosted panel led by Sam.",
    kind: "milestone",
    url: anil("2026w12#springer-letting-us-download-papers-but-not-really")
  },
  {
    date: "2026-03-12",
    title: "Evidence TAP at DEFRA's science conference",
    detail:
      "Sadiq Jaffer and Sam Reynolds ran an evidence-synthesis session for around 200 people at the DEFRA Science, Analysis and Data Professions Conference in London.",
    kind: "workshop",
    url: anil("2026w11#evidence-synthesis-at-the-defra-science-conference"),
    picture: anilImg(
      "defra-etap-2",
      "A packed conference hall at the DEFRA science conference"
    )
  },
  {
    date: "2026-02-17",
    title: "Channel News Asia documentary airs",
    detail:
      "Sam features in “Can AI genuinely improve human health and the planet?”, talking about the Conservation Evidence work to an audience of around 150 million.",
    kind: "media",
    url: sam("#media"),
    picture: {
      src: "https://www.samreynolds.org/images/media/CNA.jpg",
      alt: "Filming the Channel News Asia documentary"
    }
  },
  {
    date: "2026-02-15",
    title: "Designing the TAP, in Lego",
    detail:
      "A facilitated Lego brainstorm brought together Computer Science, Zoology, Education, CSaP and CSER to plan the newly awarded next phase of the project.",
    kind: "milestone",
    url: anil("2026w7#lego-for-the-evidence-tap"),
    picture: anilImg(
      "tap-lego-1",
      "Lego models of the evidence pipeline built during a team workshop"
    )
  },
  {
    date: "2026-02-08",
    title: "Nature: biodiversity's evidence problem",
    detail:
      "Nature reported from the Conservation Evidence conference on the plan for a constantly updated, AI-assisted evidence base with humans overseeing the process. A follow-up roundtable at the Parliamentary Office of Science and Technology came the same week.",
    kind: "media",
    url: anil("2026w6#nature-covers-our-conservation-evidence-conference")
  },
  {
    date: "2026-02-03",
    title: "Evidence champions at Pembroke",
    detail:
      "The science leads of all five UK nature conservation bodies and the JNCC gathered in Cambridge to discuss evidence-led nature recovery.",
    kind: "milestone",
    url: anil("red-pill-conservation"),
    picture: anilImg(
      "ce-champions-1",
      "Roundtable of evidence champions with laptops at Pembroke College"
    )
  },
  {
    date: "2026-01-18",
    title: "Speaking at the AI4Nature launch",
    detail:
      "Anil Madhavapeddy spoke at the IET in London on how modern AI can help nature recovery, at the launch of the cross-sector AI4Nature initiative. He was invited by Sam, a founding member.",
    kind: "talk",
    url: anil("2026w3#speaking-at-the-ai4nature-launch"),
    picture: anilImg(
      "ai4nature-2",
      "Speaking at the AI4Nature launch at the IET in London"
    )
  },
  {
    date: "2026-01-08",
    title: "Conservation Evidence conference, Cambridge",
    detail:
      "The community gathered at Pembroke College; Sam spoke on using AI to understand what works in conservation.",
    kind: "workshop",
    url: anil("2026w2#conservation-evidence-conference"),
    picture: anilImg(
      "pemb-aud-1",
      "Delegates mingling at the Conservation Evidence conference"
    )
  },
  {
    date: "2025-07-08",
    title: "Is AI poisoning the scientific literature?",
    detail:
      "Our comment in Nature proposes federated living evidence databases with human-in-the-loop review.",
    kind: "paper",
    url: anil("ai-poisoning"),
    picture: anilImg(
      "davidparkins-ai-poison",
      "Editorial illustration of AI and the scientific literature by David Parkins"
    )
  },
  {
    date: "2025-06-28",
    title: "Summer intern cohort joins the evidence work",
    detail:
      "Radhika Agrawal and Kittson Hamill joined the summer intern cohort, working on a human-in-the-loop framework for evidence-synthesis inclusion criteria and on summarising threats in the conservation evidence literature.",
    kind: "milestone",
    url: anil("eeg-interns-2025")
  },
  {
    date: "2025-05-16",
    title: "Out-of-the-box LLMs are not ready for conservation decisions",
    detail:
      "Our evaluation of LLMs for conservation decision support appeared in PLOS One.",
    kind: "paper",
    url: anil("2024-ce-llm-3")
  },
  {
    date: "2025-05-01",
    title: "AI for Nature: embrace with caution",
    detail:
      "The University of Cambridge published a feature on the horizon scan and the Conservation Evidence AI work.",
    kind: "media",
    url: sam("#media"),
    picture: {
      src: "https://www.samreynolds.org/images/media/cambridge-feature.png",
      alt: "The University of Cambridge feature “To save nature, AI needs our help”",
      pos: "top"
    }
  },
  {
    date: "2025-03-12",
    title: "AI for evidence synthesis workshop",
    detail:
      "Anil shares notes from our Cambridge workshop, held in the week a fully AI-generated paper first passed peer review.",
    kind: "workshop",
    url: anil("ai-for-evidence-synthesis-workshop"),
    picture: anilImg(
      "evidence-synth-2",
      "Participants talking between sessions at the evidence synthesis workshop"
    )
  },
  {
    date: "2024-12-05",
    title: "AI and conservation horizon scan published",
    detail:
      "The community horizon scan of AI opportunities and risks for conservation appeared in Trends in Ecology & Evolution.",
    kind: "paper",
    url: anil("2024-ai-conhorizon-1"),
    picture: anilImg(
      "2024-ai-horizon-scan-group",
      "The horizon scan authors in front of a screen of remote participants"
    )
  },
  {
    date: "2024-11-01",
    title: "First preprint on LLMs for evidence-based decision support",
    detail:
      "The first results from evaluating LLMs against the Conservation Evidence literature became available as a preprint.",
    kind: "paper",
    url: anil("2024-ce-llm-1")
  },
  {
    date: "2024-06-25",
    title: "Conservation copilots at the CCI workshop",
    detail:
      "Anil spoke on copilots and embedding evidence into conservation decision-making at the Cambridge Conservation Initiative.",
    kind: "talk",
    url: anil("80795e06-ac75-4015-b178-3cfcbb233685-1")
  },
  {
    date: "2024-06-09",
    title: "Introducing the Conservation Evidence Copilots",
    detail:
      "Anil spoke to the AI@Cam team about the project's plan to accelerate a database built from over 1.6 million screened papers and 8,600 summarised conservation studies.",
    kind: "media",
    url: anil("aicam-interview-ce")
  },
  {
    date: "2024-02-05",
    title: "Selected for the ai@cam challenge",
    detail:
      "The conservation evidence AI project was chosen as one of Cambridge's flagship AI research challenges.",
    kind: "milestone",
    url: anil("aicn-in-aicam"),
    picture: anilImg(
      "aicn-team-feb24",
      "The project team in front of a living plant wall"
    )
  }
];

/** Hostname an entry links through to, without the www prefix. */
export const linkHost = (url: string) =>
  new URL(url).hostname.replace(/^www\./, "");

const MONTHS = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");

/** "2026-01-08" -> "8 Jan 2026", without any Date/timezone involvement. */
export const formatDate = (iso: string) => {
  const [y, m, d] = iso.split("-").map(Number);
  return `${d} ${MONTHS[m - 1]} ${y}`;
};

/** Split into upcoming (soonest first) and past (newest first). */
export const splitEvents = (all: NewsEvent[], todayIso: string) => ({
  upcoming: all
    .filter((e) => e.date > todayIso)
    .sort((a, b) => a.date.localeCompare(b.date)),
  past: all
    .filter((e) => e.date <= todayIso)
    .sort((a, b) => b.date.localeCompare(a.date))
});
